- Fixed some compiler warnings, including: Display Plugins/Bezel/GrowlBezelWindowController.m: In function '-[GrowlBezelWindowController initWithTitle:text:icon:priority:sticky:]': Display Plugins/Bezel/GrowlBezelWindowController.m:76: warning: 'panelTopLeft$y' may be used uninitialized in this function Display Plugins/Bezel/GrowlBezelWindowController.m:76: warning: 'panelTopLeft$x' may be used uninitialized in this function Display Plugins/Log/GrowlLogPrefs.h:25:5: warning: no newline at end of file Display Plugins/Log/GrowlLogDefines.h:15:61: warning: no newline at end of file RRTableView.h:21:5: warning: no newline at end of file ACImageAndTextCell.h:22:5: warning: no newline at end of file Display Plugins/MusicVideo/GrowlMusicVideoWindowView.m: In function '-[GrowlMusicVideoWindowView drawRect:]': Display Plugins/MusicVideo/GrowlMusicVideoWindowView.m:105: warning: invalid receiver type `void' Display Plugins/MusicVideo/GrowlMusicVideoWindowView.m:105: error: void value not ignored as it ought to be GrowlUDPUtils.m: In function '+[GrowlUDPUtils notificationToPacket:password:packetSize:]': GrowlUDPUtils.m:43: warning: pointer targets in assignment differ in signedness GrowlUDPUtils.m:59: warning: pointer targets in passing argument 1 of 'MD5_Final' differ in signedness GrowlUDPUtils.m: In function '+[GrowlUDPUtils registrationToPacket:password:packetSize:]': GrowlUDPUtils.m:105: warning: pointer targets in assignment differ in signedness GrowlUDPUtils.m:129: warning: pointer targets in passing argument 1 of 'MD5_Final' differ in signedness GrowlStringAdditions.m: In function '-[NSString(GrowlStringAdditions) drawWithEllipsisInRect:withAttributes:]': GrowlStringAdditions.m:23: warning: invalid receiver type `void' GrowlStringAdditions.m:23: error: void value not ignored as it ought to be
- Changed GrowlMail project to reference the new PNG image instead of the non-existing TIFF image.

--HG--
extra : convert_revision : svn%3A99687598-2e92-11dd-8019-fe7b9d601d1b/trunk%401010